language: "en"
pipeline:
- name: "SpacyNLP"
  # language model to load
  model: "en_core_web_md"
- name: SpacyTokenizer
- name: "RegexFeaturizer"
- name: "SpacyFeaturizer"
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 2
  max_ngram: 4
- name: DIETClassifier
  epochs: 100
  constrain_similarities: true
  model_confidence: softmax
- name: RegexEntityExtractor
- name: SpacyEntityExtractor
  dimensions: ["DATE", "MONEY"]
  # text will be processed with case insensitive as default
  case_sensitive: False
  # use regexes to extract entities
  use_regexes: True
- name: "EntitySynonymMapper"


policies:
 - name: MemoizationPolicy
 - name: TEDPolicy
   max_history: 5
   epochs: 50
   constrain_similarities: True
 - name: RulePolicy
